### ISSUE TITLE
Overflow Issue mangles responseCore in setMSresp

### ISSUE THREAD

**Issue by ads103** [mantonakakis1/MegaCAN#2]
Line 29 of megaCAN.cpp reads:
`respMsg.responseCore |= recMsg.data.request.varOffset << 18; //write Offset bits 10-0 to core bits 28-18`

Doing a right-shift on a 16 bit value (varOffset) breaks responseCore, because of overflow. I'd like to suggest changing the line to read: 
`respMsg.responseCore |= uint32_t(recMsg.data.request.varOffset) << 18; //write Offset bits 10-0 to core bits 28-18`

**Comment by mantonakakis1** [comment]
Great catch, I will get that updated!

**Comment by mantonakakis1** [comment]
Updated the varOffset definition rather than casting - let me know if that seems to work okay. I don't think it should cause any other issues, but just in case.

**Comment by ads103** [comment]
So far, that seems to work okay. Thank you for fixing it, thank you for making this library, and Merry Christmas.
