### ISSUE TITLE
Example output

### ISSUE THREAD

**Issue by kevindebosscher** [mantonakakis1/MegaCAN#4]
Hi Michael,

Could it be possible to have a simple example?
I just found your Lib after bashing my head for the last couples of weeks.
However I still dont get the link between Receiving CAN from MS to Arduino.
Lets say activate LEDoutput13 on arduino over CAN by MS.

**Comment by mantonakakis1** [comment]
Sure, I will throw something together this week!

**Comment by kevindebosscher** [comment]
Great, looking forward :D

**Comment by mantonakakis1** [comment]
Okay, 3 example files are now in the repo. I have not tested them yet, and they are somewhat specific to Teensy 4.0 with the FlexCAN_T4 library. However, it should be fairly clear how to convert for an implementation with a different CAN library for use with another board, and I will work on an example like that soon. I will also work on some companion explanatory material to go along with the examples when I have a chance.

**Comment by kevindebosscher** [comment]
Hi Michael,

Sending Can-data  to MS is not an issue, did that without your additional library. :)
I've issues sending Can-data FROM MS to Arduino etc.
The MS digital Can-outputs only shift 1 same byte, no unique address or bytes on all digital can outputs...

**Comment by mantonakakis1** [comment]
Hmm, that should be very simple as shown in the broadcast only example. Can you please share your hardware details (which Arduino board, CAN module, MS version? I suspect it may be a problem with your setup in TunerStudio, so if you could share a few screenshots, that would also help.

**Comment by andreibbmwe30** [comment]
hello! how do I add a dbw id to your library?
![2023-06-26_09-26-09](https://github.com/mantonakakis1/MegaCAN/assets/134093233/64323b6f-7022-49bd-829d-45030b6fb847)
