### ISSUE TITLE
Compilation failure Teensy 4.0

### ISSUE THREAD

**Issue by mistersmith01** [mantonakakis1/MegaCAN#8]
Error msg when attempting to load the broadcast only sketch>>>

In file included from c:\Users\mr_sm\Documents\Arduino\libraries\FlexCAN_T4-master/FlexCAN_T4.h:34:0,
                 from C:\Users\mr_sm\AppData\Local\Temp\.arduinoIDE-unsaved2024323-7996-1xvp9cq.02ho\sketch_apr23a\sketch_apr23a.ino:2:
c:\Users\mr_sm\Documents\Arduino\libraries\FlexCAN_T4-master/circular_buffer.h:38:10: fatal error: algorithm: No such file or directory
 #include <algorithm>
          ^~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1

Where is "algorithm" located?

**Comment by mantonakakis1** [comment]
Thanks for bringing this up - I'm in the midst of a refresh of my CAN hardware on my personal vehicle and will get this sorted out as part of that process (hopefully next week or so).

**Comment by mantonakakis1** [comment]
Actually, it would seem to be an issue with line 38 in the FlexCAN_T4 library, on line 38 of this file: https://github.com/tonton81/FlexCAN_T4/blob/master/circular_buffer.h so this might be better to raise the issue, there - but it also might be an issue with your IDE/compiler. I believe "algorithm" is a C++ standard library, so if you're having an issue with it I would guess it's an issue with your compiler. 

See for example: https://stackoverflow.com/questions/9498700/removing-include-algorithm-doesnt-break-the-code
